<?php
namespace App\Database\Seeds;

use App\Models\Articles\ArticlesModel;
use CodeIgniter\Database\Seeder;

class ArticlesSeeder extends Seeder {
    public function run() {
        $articleModel = new ArticlesModel();

		$db = \CodeIgniter\Database\Config::connect();

		$arrArticles = [];

		$arrArticles = [
            //Subcategoria Relatórios
			['image' => '', 'article_name' => 'Como gerar relatórios no sistema Unimestre?', 'slug' => 'como-gerar-relatorios-no-sistema-unimestre', 'text' => 'Mussum Ipsum, cacilds vidis litro abertis. Suco de cevadiss deixa as pessoas mais interessantis. Si num tem leite então bota uma pinga aí cumpadi! Viva Forevis aptent taciti sociosqu ad litora torquent. Atirei o pau no gatis, per gatis num morreus.', 'total_access' => 0, 'id_subcategorie' => 1, 'id_status' => 1, 'id_user_created' => 1, 'id_user_updated' => 0, 'id_user_deleted' => 0, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('0000-00-00 00:00:00'), 'deleted_at' => date('0000-00-00 00:00:00')],
			['image' => '', 'article_name' => 'Como gerar declarações no sistema Unimestre?', 'slug' => 'como-gerar-declaracoes-no-sistema-unimestre', 'text' => 'Mussum Ipsum, cacilds vidis litro abertis. Suco de cevadiss deixa as pessoas mais interessantis. Si num tem leite então bota uma pinga aí cumpadi! Viva Forevis aptent taciti sociosqu ad litora torquent. Atirei o pau no gatis, per gatis num morreus.', 'total_access' => 0, 'id_subcategorie' => 1, 'id_status' => 1, 'id_user_created' => 1, 'id_user_updated' => 0, 'id_user_deleted' => 0, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('0000-00-00 00:00:00'), 'deleted_at' => date('0000-00-00 00:00:00')],
			['image' => '', 'article_name' => 'Gerando ficha financeira do aluno.', 'slug' => 'gerando-ficha-financeira-do-aluno', 'text' => 'Mussum Ipsum, cacilds vidis litro abertis. Suco de cevadiss deixa as pessoas mais interessantis. Si num tem leite então bota uma pinga aí cumpadi! Viva Forevis aptent taciti sociosqu ad litora torquent. Atirei o pau no gatis, per gatis num morreus.', 'total_access' => 0, 'id_subcategorie' => 1, 'id_status' => 1, 'id_user_created' => 1, 'id_user_updated' => 0, 'id_user_deleted' => 0, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('0000-00-00 00:00:00'), 'deleted_at' => date('0000-00-00 00:00:00')],
			['image' => '', 'article_name' => 'Erro ao gerar a ata de assinatura.', 'slug' => 'erro-ao-gerar-a-ata-de-assinatura', 'text' => 'Mussum Ipsum, cacilds vidis litro abertis. Suco de cevadiss deixa as pessoas mais interessantis. Si num tem leite então bota uma pinga aí cumpadi! Viva Forevis aptent taciti sociosqu ad litora torquent. Atirei o pau no gatis, per gatis num morreus.', 'total_access' => 0, 'id_subcategorie' => 1, 'id_status' => 1, 'id_user_created' => 1, 'id_user_updated' => 0, 'id_user_deleted' => 0, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('0000-00-00 00:00:00'), 'deleted_at' => date('0000-00-00 00:00:00')],
			['image' => '', 'article_name' => 'Problema ao gerar o histórico do aluno.', 'slug' => 'problema-ao-gerar-o-historico-do-aluno', 'text' => 'Mussum Ipsum, cacilds vidis litro abertis. Suco de cevadiss deixa as pessoas mais interessantis. Si num tem leite então bota uma pinga aí cumpadi! Viva Forevis aptent taciti sociosqu ad litora torquent. Atirei o pau no gatis, per gatis num morreus.', 'total_access' => 0, 'id_subcategorie' => 1, 'id_status' => 1, 'id_user_created' => 1, 'id_user_updated' => 0, 'id_user_deleted' => 0, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('0000-00-00 00:00:00'), 'deleted_at' => date('0000-00-00 00:00:00')],
			//Subacategoria Boletos
            ['image' => '', 'article_name' => 'Boleto do aluno sem código de barras.', 'slug' => 'boleto-do-aluno-sem-codigo-de-barras', 'text' => 'Mussum Ipsum, cacilds vidis litro abertis. Suco de cevadiss deixa as pessoas mais interessantis. Si num tem leite então bota uma pinga aí cumpadi! Viva Forevis aptent taciti sociosqu ad litora torquent. Atirei o pau no gatis, per gatis num morreus.', 'total_access' => 0, 'id_subcategorie' => 2, 'id_status' => 1, 'id_user_created' => 1, 'id_user_updated' => 0, 'id_user_deleted' => 0, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('0000-00-00 00:00:00'), 'deleted_at' => date('0000-00-00 00:00:00')],
			['image' => '', 'article_name' => 'Erro ao realizar o lançamento do boleto.', 'slug' => 'erro-ao-realizar-o-lancamento-do-boleto', 'text' => 'Mussum Ipsum, cacilds vidis litro abertis. Suco de cevadiss deixa as pessoas mais interessantis. Si num tem leite então bota uma pinga aí cumpadi! Viva Forevis aptent taciti sociosqu ad litora torquent. Atirei o pau no gatis, per gatis num morreus.', 'total_access' => 0, 'id_subcategorie' => 2, 'id_status' => 1, 'id_user_created' => 1, 'id_user_updated' => 0, 'id_user_deleted' => 0, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('0000-00-00 00:00:00'), 'deleted_at' => date('0000-00-00 00:00:00')],
			['image' => '', 'article_name' => 'Problema ao gerar o boleto do aluno.', 'slug' => 'problema-ao-gerar-o-boleto-do-aluno', 'text' => 'Mussum Ipsum, cacilds vidis litro abertis. Suco de cevadiss deixa as pessoas mais interessantis. Si num tem leite então bota uma pinga aí cumpadi! Viva Forevis aptent taciti sociosqu ad litora torquent. Atirei o pau no gatis, per gatis num morreus.', 'total_access' => 0, 'id_subcategorie' => 2, 'id_status' => 1, 'id_user_created' => 1, 'id_user_updated' => 0, 'id_user_deleted' => 0, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('0000-00-00 00:00:00'), 'deleted_at' => date('0000-00-00 00:00:00')],
			['image' => '', 'article_name' => 'Alterar a data de vencimento do boleto.', 'slug' => 'alterar-a-data-de-vencimento-do-boleto', 'text' => 'Mussum Ipsum, cacilds vidis litro abertis. Suco de cevadiss deixa as pessoas mais interessantis. Si num tem leite então bota uma pinga aí cumpadi! Viva Forevis aptent taciti sociosqu ad litora torquent. Atirei o pau no gatis, per gatis num morreus.', 'total_access' => 0, 'id_subcategorie' => 2, 'id_status' => 1, 'id_user_created' => 1, 'id_user_updated' => 0, 'id_user_deleted' => 0, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('0000-00-00 00:00:00'), 'deleted_at' => date('0000-00-00 00:00:00')],
			['image' => '', 'article_name' => 'Como gerar boleto no sistema Unimestre?', 'slug' => 'como-gerar-boleto-no-sistema-unimestre', 'text' => 'Mussum Ipsum, cacilds vidis litro abertis. Suco de cevadiss deixa as pessoas mais interessantis. Si num tem leite então bota uma pinga aí cumpadi! Viva Forevis aptent taciti sociosqu ad litora torquent. Atirei o pau no gatis, per gatis num morreus.', 'total_access' => 0, 'id_subcategorie' => 2, 'id_status' => 1, 'id_user_created' => 1, 'id_user_updated' => 0, 'id_user_deleted' => 0, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('0000-00-00 00:00:00'), 'deleted_at' => date('0000-00-00 00:00:00')],
            //Subacategoria Alterar Senha
            ['image' => '', 'article_name' => 'Como alterar a senha de acesso do usuário?', 'slug' => 'como-alterar-a-senha-de-acesso-do-usuario', 'text' => 'Mussum Ipsum, cacilds vidis litro abertis. Suco de cevadiss deixa as pessoas mais interessantis. Si num tem leite então bota uma pinga aí cumpadi! Viva Forevis aptent taciti sociosqu ad litora torquent. Atirei o pau no gatis, per gatis num morreus.', 'total_access' => 0, 'id_subcategorie' => 3, 'id_status' => 1, 'id_user_created' => 1, 'id_user_updated' => 0, 'id_user_deleted' => 0, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('0000-00-00 00:00:00'), 'deleted_at' => date('0000-00-00 00:00:00')],
            //Subacategoria Matrícula do Aluno
            ['image' => '', 'article_name' => 'Não consigo realizar a matrícula do aluno em curso.', 'slug' => 'nao-consigo-realizar-a-matricula-do-aluno-em-curso', 'text' => 'Mussum Ipsum, cacilds vidis litro abertis. Suco de cevadiss deixa as pessoas mais interessantis. Si num tem leite então bota uma pinga aí cumpadi! Viva Forevis aptent taciti sociosqu ad litora torquent. Atirei o pau no gatis, per gatis num morreus.', 'total_access' => 0, 'id_subcategorie' => 4, 'id_status' => 1, 'id_user_created' => 1, 'id_user_updated' => 0, 'id_user_deleted' => 0, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('0000-00-00 00:00:00'), 'deleted_at' => date('0000-00-00 00:00:00')],
			['image' => '', 'article_name' => 'Como alterar o responsável acadêmico da ficha de cadastro do aluno?', 'slug' => 'como-alterar-o-responsavel-academico-da-ficha-de-cadastro-do-aluno', 'text' => 'Mussum Ipsum, cacilds vidis litro abertis. Suco de cevadiss deixa as pessoas mais interessantis. Si num tem leite então bota uma pinga aí cumpadi! Viva Forevis aptent taciti sociosqu ad litora torquent. Atirei o pau no gatis, per gatis num morreus.', 'total_access' => 0, 'id_subcategorie' => 4, 'id_status' => 1, 'id_user_created' => 1, 'id_user_updated' => 0, 'id_user_deleted' => 0, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('0000-00-00 00:00:00'), 'deleted_at' => date('0000-00-00 00:00:00')],
			['image' => '', 'article_name' => 'Não consigo cadastrar o CPF do responsável financeiro.', 'slug' => 'nao-consigo-cadastrar-o-cpf-do-responsavel-financeiro', 'text' => 'Mussum Ipsum, cacilds vidis litro abertis. Suco de cevadiss deixa as pessoas mais interessantis. Si num tem leite então bota uma pinga aí cumpadi! Viva Forevis aptent taciti sociosqu ad litora torquent. Atirei o pau no gatis, per gatis num morreus.', 'total_access' => 0, 'id_subcategorie' => 4, 'id_status' => 1, 'id_user_created' => 1, 'id_user_updated' => 0, 'id_user_deleted' => 0, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('0000-00-00 00:00:00'), 'deleted_at' => date('0000-00-00 00:00:00')],
			['image' => '', 'article_name' => 'Como emitir o contrato de matrícula?', 'slug' => 'como-emitir-o-contrato-de-matricula', 'text' => 'Mussum Ipsum, cacilds vidis litro abertis. Suco de cevadiss deixa as pessoas mais interessantis. Si num tem leite então bota uma pinga aí cumpadi! Viva Forevis aptent taciti sociosqu ad litora torquent. Atirei o pau no gatis, per gatis num morreus.', 'total_access' => 0, 'id_subcategorie' => 4, 'id_status' => 1, 'id_user_created' => 1, 'id_user_updated' => 0, 'id_user_deleted' => 0, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('0000-00-00 00:00:00'), 'deleted_at' => date('0000-00-00 00:00:00')],
			['image' => '', 'article_name' => 'Como inserir disciplinas da grade do aluno?', 'slug' => 'como-inserir-disciplinas-da-grade-do-aluno', 'text' => 'Mussum Ipsum, cacilds vidis litro abertis. Suco de cevadiss deixa as pessoas mais interessantis. Si num tem leite então bota uma pinga aí cumpadi! Viva Forevis aptent taciti sociosqu ad litora torquent. Atirei o pau no gatis, per gatis num morreus.', 'total_access' => 0, 'id_subcategorie' => 4, 'id_status' => 1, 'id_user_created' => 1, 'id_user_updated' => 0, 'id_user_deleted' => 0, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('0000-00-00 00:00:00'), 'deleted_at' => date('0000-00-00 00:00:00')],
            //Subacategoria Lançamento de Notas
            ['image' => '', 'article_name' => 'O sistema não faz o cálculo da média?', 'slug' => 'o-sistema-nao-faz-o-calculo-da-media', 'text' => 'Mussum Ipsum, cacilds vidis litro abertis. Suco de cevadiss deixa as pessoas mais interessantis. Si num tem leite então bota uma pinga aí cumpadi! Viva Forevis aptent taciti sociosqu ad litora torquent. Atirei o pau no gatis, per gatis num morreus.', 'total_access' => 0, 'id_subcategorie' => 5, 'id_status' => 1, 'id_user_created' => 1, 'id_user_updated' => 0, 'id_user_deleted' => 0, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('0000-00-00 00:00:00'), 'deleted_at' => date('0000-00-00 00:00:00')],
			['image' => '', 'article_name' => 'Como lançar notas no sistema?', 'slug' => 'como-lancar-notas-no-sistema', 'text' => 'Mussum Ipsum, cacilds vidis litro abertis. Suco de cevadiss deixa as pessoas mais interessantis. Si num tem leite então bota uma pinga aí cumpadi! Viva Forevis aptent taciti sociosqu ad litora torquent. Atirei o pau no gatis, per gatis num morreus.', 'total_access' => 0, 'id_subcategorie' => 5, 'id_status' => 1, 'id_user_created' => 1, 'id_user_updated' => 0, 'id_user_deleted' => 0, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('0000-00-00 00:00:00'), 'deleted_at' => date('0000-00-00 00:00:00')],
            //Subacategoria Boletim
            ['image' => '', 'article_name' => 'Como gerar o boletim do aluno?', 'slug' => 'como-gerar-o-boletim-do-aluno', 'text' => 'Mussum Ipsum, cacilds vidis litro abertis. Suco de cevadiss deixa as pessoas mais interessantis. Si num tem leite então bota uma pinga aí cumpadi! Viva Forevis aptent taciti sociosqu ad litora torquent. Atirei o pau no gatis, per gatis num morreus.', 'total_access' => 0, 'id_subcategorie' => 6, 'id_status' => 1, 'id_user_created' => 1, 'id_user_updated' => 0, 'id_user_deleted' => 0, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('0000-00-00 00:00:00'), 'deleted_at' => date('0000-00-00 00:00:00')],
			['image' => '', 'article_name' => 'Como alterar a nota de uma disciplina no boletim?', 'slug' => 'como-alterar-a-nota-de-uma-disciplina-no-boletim', 'text' => 'Mussum Ipsum, cacilds vidis litro abertis. Suco de cevadiss deixa as pessoas mais interessantis. Si num tem leite então bota uma pinga aí cumpadi! Viva Forevis aptent taciti sociosqu ad litora torquent. Atirei o pau no gatis, per gatis num morreus.', 'total_access' => 0, 'id_subcategorie' => 6, 'id_status' => 1, 'id_user_created' => 1, 'id_user_updated' => 0, 'id_user_deleted' => 0, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('0000-00-00 00:00:00'), 'deleted_at' => date('0000-00-00 00:00:00')],
            //Subacategoria Financeiro
            ['image' => '', 'article_name' => 'Como gerar lançamentos no sistema?', 'slug' => 'como-gerar-lancamentos-no-sistema', 'text' => 'Mussum Ipsum, cacilds vidis litro abertis. Suco de cevadiss deixa as pessoas mais interessantis. Si num tem leite então bota uma pinga aí cumpadi! Viva Forevis aptent taciti sociosqu ad litora torquent. Atirei o pau no gatis, per gatis num morreus.', 'total_access' => 0, 'id_subcategorie' => 7, 'id_status' => 1, 'id_user_created' => 1, 'id_user_updated' => 0, 'id_user_deleted' => 0, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('0000-00-00 00:00:00'), 'deleted_at' => date('0000-00-00 00:00:00')],
			['image' => '', 'article_name' => 'Como abrir um caixa no sistema?', 'slug' => 'como-abrir-um-caixa-no-sistema', 'text' => 'Mussum Ipsum, cacilds vidis litro abertis. Suco de cevadiss deixa as pessoas mais interessantis. Si num tem leite então bota uma pinga aí cumpadi! Viva Forevis aptent taciti sociosqu ad litora torquent. Atirei o pau no gatis, per gatis num morreus.', 'total_access' => 0, 'id_subcategorie' => 7, 'id_status' => 1, 'id_user_created' => 1, 'id_user_updated' => 0, 'id_user_deleted' => 0, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('0000-00-00 00:00:00'), 'deleted_at' => date('0000-00-00 00:00:00')],
            //Subacategoria Declarações
            ['image' => '', 'article_name' => 'Solicitando declarações no sistema.', 'slug' => 'solicitando-declaracoes-no-sistema', 'text' => 'Mussum Ipsum, cacilds vidis litro abertis. Suco de cevadiss deixa as pessoas mais interessantis. Si num tem leite então bota uma pinga aí cumpadi! Viva Forevis aptent taciti sociosqu ad litora torquent. Atirei o pau no gatis, per gatis num morreus.', 'total_access' => 0, 'id_subcategorie' => 8, 'id_status' => 1, 'id_user_created' => 1, 'id_user_updated' => 0, 'id_user_deleted' => 0, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('0000-00-00 00:00:00'), 'deleted_at' => date('0000-00-00 00:00:00')],
			['image' => '', 'article_name' => 'Como solicitar uma declaração de matrícula?', 'slug' => 'como-solicitar-uma-declaracao-de-matricula', 'text' => 'Mussum Ipsum, cacilds vidis litro abertis. Suco de cevadiss deixa as pessoas mais interessantis. Si num tem leite então bota uma pinga aí cumpadi! Viva Forevis aptent taciti sociosqu ad litora torquent. Atirei o pau no gatis, per gatis num morreus.', 'total_access' => 0, 'id_subcategorie' => 8, 'id_status' => 1, 'id_user_created' => 1, 'id_user_updated' => 0, 'id_user_deleted' => 0, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('0000-00-00 00:00:00'), 'deleted_at' => date('0000-00-00 00:00:00')],
        ];

		foreach ($arrArticles as $value) {
			if (is_array($value)) {
				$inputs = [
					'image' => $value['image'],
					'article_name' => $value['article_name'],
					'slug' => $value['slug'],
					'text' => $value['text'],
					'total_access' => $value['total_access'],
					'id_subcategorie' => $value['id_subcategorie'],
					'id_status' => $value['id_status'],
					'id_user_created' => $value['id_user_created'],
					'id_user_updated' => $value['id_user_updated'],
					'id_user_deleted' => $value['id_user_deleted'],
					'created_at' => $value['created_at'],
					'updated_at' => $value['updated_at'],
					'deleted_at' => $value['deleted_at']
				];
			}

			$db->disableForeignKeyChecks();
			$articleModel->save($inputs);
			$db->enableForeignKeyChecks();
		}
    }
}